/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.Amigo;
import dao.AmigoDAO;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import model.Ferramenta;
import dao.FerramentaDAO;
import java.sql.SQLException;
import model.Emprestimo;
import dao.EmprestimoDAO;

/**
 *
 * @author Administrator
 */
public class FrmMenuRelatorio extends javax.swing.JFrame {

    private AmigoDAO amigoDAO;
    private FerramentaDAO ferramentaDAO;
    private EmprestimoDAO emprestimoDAO;
    
    /**
     * Creates new form FrmMenuRelatorio
     */
    public FrmMenuRelatorio() {
        initComponents();
        this.amigoDAO = new AmigoDAO();
        this.ferramentaDAO = new FerramentaDAO();
        this.emprestimoDAO = EmprestimoDAO.getInstance();
        this.carregaTabelaFerramentaDisponivel();
        this.carregaTabelaFerramentaIndisponivel();
        this.carregaTabelaEmprestimo();
        this.procuraAmigoMaisEmprestimo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTFerramentasdisponivel = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTFerramentaindisponivel1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTemprestimo1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jTFAmigoquemaispegou = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTFAmigoquemaispegou1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTFerramentasdisponivel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Marca", "Custo", "Status"
            }
        ));
        jTFerramentasdisponivel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTFerramentasdisponivelAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jTFerramentasdisponivel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFerramentasdisponivelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTFerramentasdisponivel);

        jLabel1.setText("Ferramenta disponivel:");

        jLabel2.setText("Ferramenta insponivel:");

        jTFerramentaindisponivel1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Marca", "Custo", "Status"
            }
        ));
        jTFerramentaindisponivel1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTFerramentaindisponivel1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jTFerramentaindisponivel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFerramentaindisponivel1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTFerramentaindisponivel1);

        jLabel3.setText("Emprestimos:");

        jTemprestimo1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "amigo", "quantidade ferramentas", "custo", "data_emprestimo", "data_devolução", "dias restantes", "status"
            }
        ));
        jTemprestimo1.setToolTipText("");
        jTemprestimo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTemprestimo1MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTemprestimo1);

        jLabel4.setText("Amigo que mais pegou emprestimo:");

        jLabel5.setText("Amigo que nunca devolveu:");

        jTFAmigoquemaispegou1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFAmigoquemaispegou1ActionPerformed(evt);
            }
        });

        jButton3.setText("Emprestimos");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setText("Cadastrar emprestimos");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Amigos");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Cadastrar amgos");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Ver emprestimos");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Ver amigos");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Sair");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(167, 167, 167)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(140, 140, 140)
                .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(44, 44, 44))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTFAmigoquemaispegou, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTFAmigoquemaispegou1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 822, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTFAmigoquemaispegou, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTFAmigoquemaispegou1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFerramentasdisponivelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTFerramentasdisponivelAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFerramentasdisponivelAncestorAdded

    private void jTFerramentasdisponivelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFerramentasdisponivelMouseClicked

    }//GEN-LAST:event_jTFerramentasdisponivelMouseClicked

    private void jTFerramentaindisponivel1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTFerramentaindisponivel1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFerramentaindisponivel1AncestorAdded

    private void jTFerramentaindisponivel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFerramentaindisponivel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFerramentaindisponivel1MouseClicked

    private void jTemprestimo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTemprestimo1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTemprestimo1MouseClicked

    private void jTFAmigoquemaispegou1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFAmigoquemaispegou1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFAmigoquemaispegou1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        FrmMenuCadastrarEmprestimo objeto = new FrmMenuCadastrarEmprestimo();
        objeto.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    public void carregaTabelaFerramentaDisponivel() {
        DefaultTableModel modelo = (DefaultTableModel) this.jTFerramentasdisponivel.getModel();
        modelo.setNumRows(0);  // Limpa a tabela antes de recarregar

        ArrayList<Ferramenta> minhalista = ferramentaDAO.getMinhaLista();  // Lista de Ferramentas

        String change;
        for (Ferramenta a : minhalista) {
            if (a.getStatus() == 1) {
                change = "Disponível";
                modelo.addRow(new Object[]{
                    a.getId(),
                    a.getNome(),
                    a.getMarca(),
                    a.getCusto(),
                    change
                });
            }
        }
    }
    
    public void carregaTabelaFerramentaIndisponivel() {
        DefaultTableModel modelo = (DefaultTableModel) this.jTFerramentaindisponivel1.getModel();
        modelo.setNumRows(0);  // Limpa a tabela antes de recarregar

        ArrayList<Ferramenta> minhalista = ferramentaDAO.getMinhaLista();  // Lista de Ferramentas

        String change;
        for (Ferramenta a : minhalista) {
            if (a.getStatus() == 0) {
                change = "Indisponível";
                modelo.addRow(new Object[]{
                    a.getId(),
                    a.getNome(),
                    a.getMarca(),
                    a.getCusto(),
                    change
                });
            }
        }
    }
    
    public void carregaTabelaEmprestimo() {
        DefaultTableModel modelo = (DefaultTableModel) this.jTemprestimo1.getModel();
        modelo.setNumRows(0); // Limpa a tabela antes de preencher

        // Obtém a lista de empréstimos do DAO
        ArrayList<Emprestimo> minhalista = emprestimoDAO.listarEmprestimos();

        for (Emprestimo emprestimo : minhalista) {
            double valorTotal = emprestimo.calcularValorTotal();
            String situacaoEmprestimo;

            // Define o status textual com base no código do status
            switch (emprestimo.getStatus().getCodigo()) {
                case 1:
                    situacaoEmprestimo = "Em aberto";
                    break;
                case 2:
                    situacaoEmprestimo = "Finalizado";
                    break;
                case 3:
                    situacaoEmprestimo = "Atrasado";
                    break;
                default:
                    situacaoEmprestimo = "Desconhecido";
                    break;
            }

            // Cálculo do tempo restante
            long diasRestantes = emprestimo.tempoRestante(
                    emprestimo.getDataInicial().toLocalDate(),
                    emprestimo.getDataDevolucao().toLocalDate()
            );

            String nomeAmigo = "";
            try {
                // Tenta obter o nome do amigo
                nomeAmigo = emprestimoDAO.buscarNomeAmigoPorId(emprestimo.getIdAmigo());
            } catch (SQLException e) {
                // Caso ocorra um erro na consulta ao banco, exibe um erro no console
                e.printStackTrace(); // Exibe o stack trace do erro
                nomeAmigo = "Erro ao buscar nome"; // Mensagem padrão caso haja erro
            }

            // Adiciona os dados na tabela
            modelo.addRow(new Object[]{
                emprestimo.getIdEmprestimo(),
                nomeAmigo,
                emprestimo.qtdFerramentasEmprestimo(emprestimo.getIdEmprestimo()),
                emprestimo.getCustoTotal(),
                emprestimo.getDataInicial(),
                emprestimo.getDataDevolucao(),
                diasRestantes,
                situacaoEmprestimo
            });
        }
    }
    
    private void procuraAmigoMaisEmprestimo(){
        ArrayList<Emprestimo> emprestimos = emprestimoDAO.listarEmprestimos();
        ArrayList<Amigo> amigos = amigoDAO.getMinhaLista();
        ArrayList<Integer> emprestimoPorAmigo = new ArrayList<>();
        
        for(int i = 0; i < amigos.size(); i++){
            emprestimoPorAmigo.add(0);
            for(int j = 0; j < emprestimos.size(); j++){
                if(amigos.get(i).getId() == emprestimos.get(j).getIdAmigo()){
                    emprestimoPorAmigo.set(i, emprestimoPorAmigo.get(i)+1);
                }
            }
        }
        
        int maior = 0;
        for(int i : emprestimoPorAmigo){
            if(i > maior){
                maior = i;
            }
        }
        
        int index = emprestimoPorAmigo.indexOf(maior);
        
        jTFAmigoquemaispegou.setText(amigos.get(index).getNome());
    }
    
    private void nuncaDevolveu(){
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuRelatorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTFAmigoquemaispegou;
    private javax.swing.JTextField jTFAmigoquemaispegou1;
    private javax.swing.JTable jTFerramentaindisponivel1;
    private javax.swing.JTable jTFerramentasdisponivel;
    private javax.swing.JTable jTemprestimo1;
    // End of variables declaration//GEN-END:variables
}
